server:
  port: 8080
  servlet:
    context-path: /girl
  tomcat:
    uri-encoding: UTF-8
cupSize: A

# Single file max size
multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb


#spring:
#  profiles:
#    active: dev
#   #数据库连接信息
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mall
#    username: root
#    password: 1234
#    show-sql: true

#设置提供的服务名
spring:
  application:
    name: javademo-tyh-service-base
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    show-sql: true

#设置自己启动的端口
server:
  port: 8080

#mybatis plus
mybatis-plus:
  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  mapper-locations: classpath*:/mapper/*.xml
  #指明实体扫描(多个package用逗号或者分号分隔)
  typeAliasesPackage: com.gt.entity
  global-config:
    #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
    id-type: 0
    #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
    field-strategy: 2
    #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
    db-column-underline: true
    #是否动态刷新mapper
    refresh-mapper: false
    #数据库大写命名下划线转换
    #capital-mode: true

web:
  #服务地址
  homeUrl: http://192.168.1.5:8080/
  #图片前缀
  picUrl: http://39.105.200.221:80/

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 150000 #socket连接超时时长
  connectTimeout: 60000 #连接tracker服务器超时时长
  resHost: 39.105.200.221
  storagePort: 80
  thumbImage: #缩略图生成参数，可选
      width: 150
      height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 39.105.200.221:22122

#spring:
#  http:
#    multipart:
#      max-file-size: 100MB # 最大支持文件大小
#      max-request-size: 100MB # 最大支持请求大小




logging:
  config: classpath:logback.xml
















